/**
 * Maps Storyblok blok `component` names → Astro files.
 * Keep in sync with `storyblok/components.json`.
 */
export const storyblokComponents = {
  page: 'storyblok/Page',

  teaser: 'storyblok/Teaser',
  grid: 'storyblok/Grid',
  feature: 'storyblok/Feature',

  // ── Universal page sections (friendly names in Storyblok UI) ──
  hero_service: 'storyblok/sections/HeroService',
  hero_split: 'storyblok/sections/HeroSplit',
  hero_centered: 'storyblok/sections/HeroCentered',
  section_intro: 'storyblok/sections/SectionIntro',
  intro_split: 'storyblok/sections/IntroSplit',
  content_image_left: 'storyblok/sections/ContentImageLeft',
  content_image_right: 'storyblok/sections/ContentImageRight',
  split_content: 'storyblok/sections/SplitContent',
  service_card_grid: 'storyblok/sections/ServiceCardGrid',
  service_card: 'storyblok/sections/ServiceCard',
  value_metrics: 'storyblok/sections/ValueMetrics',
  metric_item: 'storyblok/sections/MetricItem',
  numbered_list_split: 'storyblok/sections/NumberedListSplit',
  numbered_item: 'storyblok/sections/NumberedItem',
  why_choose_accordion: 'storyblok/sections/WhyChooseAccordion',
  accordion_item: 'storyblok/sections/AccordionItem',
  faq_section: 'storyblok/sections/FaqSection',
  faq_item: 'storyblok/sections/FaqItem',
  testimonials_slider: 'storyblok/sections/TestimonialsSlider',
  testimonial_item: 'storyblok/sections/TestimonialItem',
  contact_section: 'storyblok/sections/ContactSection',
  reviews_grid: 'storyblok/sections/ReviewsGrid',
  review_item: 'storyblok/sections/ReviewItem',
  custom_html: 'storyblok/sections/CustomHtml',
  button_link: 'storyblok/sections/ButtonLink',
  wide_image: 'storyblok/sections/WideImage',
  tabs_section: 'storyblok/sections/TabsSection',
  tab_item: 'storyblok/sections/TabItem',
  legal_page: 'storyblok/sections/LegalPage',
  service_card_list: 'storyblok/sections/ServiceCardList',
  service_list_item: 'storyblok/sections/ServiceListItem',
  contact_form_section: 'storyblok/sections/ContactFormSection',
  contact_info_section: 'storyblok/sections/ContactInfoSection',
  contact_location: 'storyblok/sections/ContactLocation',

  onboarding_process: 'storyblok/sections/OnboardingProcess',
  onboarding_phase: 'storyblok/sections/OnboardingPhase',

  problems_grid: 'storyblok/sections/ProblemsGrid',
  problem_item: 'storyblok/sections/ProblemItem',
  service_areas: 'storyblok/sections/ServiceAreas',
  accreditations: 'storyblok/sections/Accreditations',
  awards_banner: 'storyblok/sections/AwardsBanner',
  location_cards: 'storyblok/sections/LocationCards',

  // Homepage / preset sections
  award_marquee: 'storyblok/sections/presets/AwardMarquee',
  tired_of_waiting: 'storyblok/sections/presets/TiredOfWaiting',
  strategic_support: 'storyblok/sections/presets/StrategicSupport',
  it_services_section: 'storyblok/sections/presets/ItServicesSection',
  ebook_cta: 'storyblok/sections/EbookCta',
  trust_checklist: 'storyblok/sections/presets/TrustChecklist',
  blog_grid: 'storyblok/sections/presets/BlogGrid',
  inc_award: 'storyblok/sections/presets/IncAward',
  industries_grid: 'storyblok/sections/IndustriesGrid',
  industry_card: 'storyblok/sections/IndustryCard',

  hero_industry: 'storyblok/sections/HeroIndustrySection',
  hero_service_detail: 'storyblok/sections/HeroServiceDetailSection',
  service_detail_intro: 'storyblok/sections/ServiceDetailIntroSection',
  article_with_sidebar: 'storyblok/sections/ArticleWithSidebarSection',
  hero_blog_post: 'storyblok/sections/HeroBlogPostSection',
  blog_listing: 'storyblok/sections/BlogListing',
  blog_category_listing: 'storyblok/sections/BlogCategoryListing',
  author_profile: 'storyblok/sections/AuthorProfile',
  related_posts: 'storyblok/sections/RelatedPostsSection',
} as const;

export const pageSectionWhitelist = [
  'hero_service',
  'section_intro',
  'intro_split',
  'content_image_left',
  'content_image_right',
  'service_card_grid',
  'value_metrics',
  'numbered_list_split',
  'why_choose_accordion',
  'faq_section',
  'testimonials_slider',
  'contact_section',
  'reviews_grid',
  'custom_html',
  'wide_image',
  'tabs_section',
  'legal_page',
  'service_card_list',
  'contact_form_section',
  'contact_info_section',
  // Legacy blocks still on seeded pages (not addable in editor)
  'hero_split',
  'problems_grid',
  'service_areas',
  'accreditations',
  'awards_banner',
  'award_marquee',
  'tired_of_waiting',
  'strategic_support',
  'it_services_section',
  'inc_award',
  'industries_grid',
  'ebook_cta',
  'trust_checklist',
  'blog_grid',
  'location_cards',
  'hero_centered',
  'split_content',
  'hero_industry',
  'hero_service_detail',
  'service_detail_intro',
  'article_with_sidebar',
  'hero_blog_post',
  'blog_listing',
  'blog_category_listing',
  'author_profile',
  'related_posts',
  'industry_card',
] as const;
